FROM openjdk:17
COPY ./target/ecommerce-0.0.1-SNAPSHOT.jar ecommerce-0.0.1-SNAPSHOT.jar
ARG STRIPE_PUBLIC_API_KEY
ENV STRIPE_PUBLIC_API_KEY ${STRIPE_PUBLIC_API_KEY}
ARG STRIPE_SECRET_API_KEY
ENV STRIPE_SECRET_API_KEY ${STRIPE_SECRET_API_KEY}
ARG SPRING_MAIL_USERNAME
ENV SPRING_MAIL_USERNAME ${SPRING_MAIL_USERNAME}
ARG SPRING_MAIL_PASSWORD
ENV SPRING_MAIL_PASSWORD ${SPRING_MAIL_PASSWORD}
CMD STRIPE_PUBLIC_API_KEY=$STRIPE_PUBLIC_API_KEY SPRING_MAIL_USERNAME=$SPRING_MAIL_USERNAME SPRING_MAIL_PASSWORD=$SPRING_MAIL_PASSWORD java -jar ecommerce-0.0.1-SNAPSHOT.jar